version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./:/data  # 修正: src → ./

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/data  # 修正: src → ./
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data

  db:
    build: ./infra/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel_nagoyameshi
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: